<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prop_position extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Prop_pos_model');
    } 

    /*
     * Listing of prop_pos
     */
    function index()
    {
        $data['prop_pos'] = $this->Prop_pos_model->get_all_prop_pos();
        
        $data['_view'] = 'prop_po/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new prop_po
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'prop_id' => $this->input->post('prop_id'),
				'position' => $this->input->post('position'),
            );
            
            $prop_po_id = $this->Prop_pos_model->add_prop_po($params);
            redirect('prop_position/index');
        }
        else
        {
			$this->load->model('Property_model');
			$data['all_property'] = $this->Property_model->get_all_property();
            
            $data['_view'] = 'prop_po/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a prop_po
     */
    function edit($id)
    {   
        // check if the prop_po exists before trying to edit it
        $data['prop_po'] = $this->Prop_pos_model->get_prop_po($id);
        
        if(isset($data['prop_po']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'prop_id' => $this->input->post('prop_id'),
					'position' => $this->input->post('position'),
                );

                $this->Prop_pos_model->update_prop_po($id,$params);            
                redirect('prop_position/index');
            }
            else
            {
				$this->load->model('Property_model');
				$data['all_property'] = $this->Property_model->get_all_property();

                $data['_view'] = 'prop_po/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The prop_po you are trying to edit does not exist.');
    } 

    /*
     * Deleting prop_po
     */
    function remove($id)
    {
        $prop_po = $this->Prop_pos_model->get_prop_po($id);

        // check if the prop_po exists before trying to delete it
        if(isset($prop_po['id']))
        {
            $this->Prop_pos_model->delete_prop_po($id);
            redirect('prop_position/index');
        }
        else
            show_error('The prop_po you are trying to delete does not exist.');
    }
    
}
