<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Uk_town extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Uk_town_model');
    } 

    /*
     * Listing of uk_towns
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('uk_town/index?');
        $config['total_rows'] = $this->Uk_town_model->get_all_uk_towns_count();
        $this->pagination->initialize($config);

        $data['uk_towns'] = $this->Uk_town_model->get_all_uk_towns($params);
        
        $data['_view'] = 'uk_town/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new uk_town
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'eastings' => $this->input->post('eastings'),
                'northings' => $this->input->post('northings'),
                'latitude' => $this->input->post('latitude'),
                'longitude' => $this->input->post('longitude'),
                'town' => $this->input->post('town'),
                'region' => $this->input->post('region'),
                'uk_region' => $this->input->post('uk_region'),
                'country' => $this->input->post('country'),
                'country_string' => $this->input->post('country_string'),
            );
            
            $uk_town_id = $this->Uk_town_model->add_uk_town($params);
            redirect('uk_town/index');
        }
        else
        {            
            $data['_view'] = 'uk_town/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a uk_town
     */
    function edit($postcode)
    {   
        // check if the uk_town exists before trying to edit it
        $data['uk_town'] = $this->Uk_town_model->get_uk_town($postcode);
        
        if(isset($data['uk_town']['postcode']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'eastings' => $this->input->post('eastings'),
                    'northings' => $this->input->post('northings'),
                    'latitude' => $this->input->post('latitude'),
                    'longitude' => $this->input->post('longitude'),
                    'town' => $this->input->post('town'),
                    'region' => $this->input->post('region'),
                    'uk_region' => $this->input->post('uk_region'),
                    'country' => $this->input->post('country'),
                    'country_string' => $this->input->post('country_string'),
                );

                $this->Uk_town_model->update_uk_town($postcode,$params);            
                redirect('uk_town/index');
            }
            else
            {
                $data['_view'] = 'uk_town/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The uk_town you are trying to edit does not exist.');
    } 

    /*
     * Deleting uk_town
     */
    function remove($postcode)
    {
        $uk_town = $this->Uk_town_model->get_uk_town($postcode);

        // check if the uk_town exists before trying to delete it
        if(isset($uk_town['postcode']))
        {
            $this->Uk_town_model->delete_uk_town($postcode);
            redirect('uk_town/index');
        }
        else
            show_error('The uk_town you are trying to delete does not exist.');
    }
    
}