<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feature_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get feature by prop_id
     */
    function get_feature($prop_id)
    {
        return $this->db->get_where('features',array('prop_id'=>$prop_id))->row_array();
    }
        
    /*
     * Get all features
     */
    function get_all_features()
    {
        $this->db->order_by('prop_id', 'desc');
        return $this->db->get('features')->result_array();
    }
        
    /*
     * function to add new feature
     */
    function add_feature($params)
    {
        $this->db->insert('features',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update feature
     */
    function update_feature($prop_id,$params)
    {
        $this->db->where('prop_id',$prop_id);
        return $this->db->update('features',$params);
    }
    
    /*
     * function to delete feature
     */
    function delete_feature($prop_id)
    {
        return $this->db->delete('features',array('prop_id'=>$prop_id));
    }
}
